# Site settings
title: Cherry on Top
author: Steve Cherry
email: stevenccherry@gmail.com
description: The online home of Steve Cherry.
baseurl: ""
url: "https://stevecherry.net"
repo: sccherry.github.io

twitter_username:   stevenccherry
github_username:    sccherry
linkedin_username:  sccherry
google_analytics:   UA-19261191-1

safe: true
host: 0.0.0.0
permalink: /posts/:year/:month/:day/:title/

# Build settings
markdown: kramdown

exclude: ["README.md"]
