# Site settings
title: Cherry on Top
email: stevenccherry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The online home of Steve Cherry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevecherry.net" # the base hostname & protocol for your site

twitter_username: stevenccherry
github_username:  sccherry
linkedin_username:  sccherry

safe: true

permalink: /posts/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: projects
    values:
      layout: project


collections:
  projects:
    output: true
    permalink: /projects/:path/


# Build settings
markdown: kramdown

exclude: ["README.md", "*.sublime-*"]

host: 0.0.0.0
