# Site settings
title: Cherry on Top
email: stevenccherry@gmail.com
description: The online home of Steve Cherry.
baseurl: ""
url: "http://stevecherry.net"
twitter_username: stevenccherry
github_username:  sccherry
linkedin_username:  sccherry
google_analytics: UA-19261191-1

safe: true
host: 0.0.0.0
permalink: /posts/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: projects
    values:
      layout: project

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown

exclude: ["README.md", "*.sublime-*"]
