# Site settings
title: Cherry on Top
email: stevenccherry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The online home of Steve Cherry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevecherry.net" # the base hostname & protocol for your site

twitter_username: stevenccherry
github_username:  sccherry
linkedin_username:  sccherry

safe: true

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"


# Build settings
markdown: kramdown

exclude: ["README.md", "*.sublime-*"]

host: 0.0.0.0


# Prose.io

prose:
  rooturl: "_posts"
  siteurl: "http://stevecherry.net"
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          placeholder: "Choose a category"
          options:
            - name: "Projects"
              value: "projects"
      - name: "summary"
        field:
          element: "text"
          label: "Summary"
          placeholder: "Write a summary"
      - name: "image"
        field:
          element: "text"
          label: "Image"
      - name: "date"
        field:
          element: "text"
          label: "Date"
