# Site settings
title: Cherry on Top
author: Steve Cherry
email: stevenccherry@gmail.com
description: The online home of Steve Cherry.
baseurl: ""
url: "https://stevecherry.net"
repo: sccherry.github.io

# twitter_username: stevenccherry
codepen_username: sccherry
github_username: sccherry
# linkedin_username: sccherry

safe: true
host: 0.0.0.0
permalink: /posts/:year/:month/:day/:title/

# Build settings
markdown: kramdown

exclude:
  - README.md
  - docker-compose.yml
  - CNAME
  - Makefile

plugins:
  - jekyll-feed
