---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/writing
  label: Articles
  create: documents
  match: "**/*"
  exclude: "*.js"
- type: document
  path: src/work.md
  label: Resume
- type: document
  path: src/index.md
  label: About
upload_dir: public/img/uploads
public_path: "/public/img/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
