backend:
  name: github
  repo: sccherry/sccherry.github.io # Path to your GitHub repository
  branch: main
  site_domain: sccherry.netlify.com
publish_mode: editorial_workflow
media_folder: 'public/img' # Media files will be stored in the repo under static/images/uploads
public_folder: '/public/img' # The src attribute for uploaded media will begin with /images/uploads
show_preview_links: false
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - name: 'about'
        label: 'About'
        file: 'src/index.md'
        fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'page.njk'
          - label: 'Navigation'
            name: 'eleventyNavigation'
            widget: 'object'
            collapsed: true
            fields:
              - { label: 'Key', name: 'key', type: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'resume'
        label: 'Résumé'
        file: 'src/work.md'
        fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'page.njk'
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Navigation'
            name: 'eleventyNavigation'
            widget: 'object'
            collapsed: true
            fields:
              - { label: 'Key', name: 'key', type: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'article' # Used in routes, e.g., /admin/collections/blog
    label: 'Articles' # Used in the UI
    folder: 'src/writing' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: true
        time_format: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: true
        required: false
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        options:
          - { label: 'Music', value: 'music' }
          - { label: 'Life', value: 'life' }
          - { label: 'Work', value: 'work' }
        multiple: true
        required: false
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'code' # Used in routes, e.g., /admin/collections/blog
    label: 'Code' # Used in the UI
    folder: 'src/code' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: true
        time_format: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: true
        required: false
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'HTML'
        name: 'html'
        widget: 'code'
        default_language: 'html'
        allow_language_selection: false
      - label: 'CSS'
        name: 'css'
        widget: 'code'
        default_language: 'css'
        allow_language_selection: false
      - label: 'JavaScript'
        name: 'js'
        widget: 'code'
        default_language: 'javascript'
        allow_language_selection: false
